// <auto-generated />
using System;
using KaniniAcademy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaniniAcademy.Migrations
{
    [DbContext(typeof(KaniniAcademyContext))]
    partial class KaniniAcademyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KaniniAcademy.Models.AboutTheCertificate", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Image1")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Image2")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Image3")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Image4")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Image5")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Image6")
                        .HasColumnType("longblob");

                    b.Property<string>("approtime")
                        .HasColumnType("longtext");

                    b.Property<string>("language")
                        .HasColumnType("longtext");

                    b.Property<string>("level")
                        .HasColumnType("longtext");

                    b.Property<string>("onlinecour")
                        .HasColumnType("longtext");

                    b.Property<string>("schedule")
                        .HasColumnType("longtext");

                    b.Property<string>("shareCert")
                        .HasColumnType("longtext");

                    b.HasKey("ImageId");

                    b.ToTable("AboutTheCertificates");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BlogCategory")
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<string>("Topic")
                        .HasColumnType("longtext");

                    b.HasKey("BlogId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Certificate", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CertificatePass")
                        .HasColumnType("longtext");

                    b.Property<string>("Cname")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<string>("KeySkills")
                        .HasColumnType("longtext");

                    b.Property<string>("Projects")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingFormat")
                        .HasColumnType("longtext");

                    b.Property<int?>("VideosDuration")
                        .HasColumnType("int");

                    b.HasKey("Cid");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseProvider")
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("KaniniAcademy.Models.CourseResource", b =>
                {
                    b.Property<int>("CourseResourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Video")
                        .HasColumnType("longblob");

                    b.HasKey("CourseResourceID");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseResources");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Creator", b =>
                {
                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("CreatorImage")
                        .HasColumnType("longblob");

                    b.Property<string>("CreatorJob")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatorName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Followers")
                        .HasColumnType("int");

                    b.HasKey("CreatorId");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("KaniniAcademy.Models.CtcReg", b =>
                {
                    b.Property<int>("CtcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CtcId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("CtcRegs");
                });

            modelBuilder.Entity("KaniniAcademy.Models.DetailedCertificate", b =>
                {
                    b.Property<int>("detailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AboutAns1")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns10")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns11")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns2")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns3")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns4")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns5")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns6")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns7")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns8")
                        .HasColumnType("longtext");

                    b.Property<string>("AboutAns9")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqAns1")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqAns2")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqAns3")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqAns4")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqAns5")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqQues1")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqQues2")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqQues3")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqQues4")
                        .HasColumnType("longtext");

                    b.Property<string>("FaqQues5")
                        .HasColumnType("longtext");

                    b.Property<string>("Work1")
                        .HasColumnType("longtext");

                    b.Property<string>("Work2")
                        .HasColumnType("longtext");

                    b.Property<string>("Work3")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkAns1")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkAns2")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkAns3")
                        .HasColumnType("longtext");

                    b.HasKey("detailId");

                    b.ToTable("DetailedCertificates");
                });

            modelBuilder.Entity("KaniniAcademy.Models.FreeResource", b =>
                {
                    b.Property<int>("FreeRid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Book")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Downloads")
                        .HasColumnType("int");

                    b.Property<string>("Template")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("longblob");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Video")
                        .HasColumnType("longblob");

                    b.Property<string>("mainfeature")
                        .HasColumnType("longtext");

                    b.HasKey("FreeRid");

                    b.HasIndex("CreatorId");

                    b.ToTable("FreeResources");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Note", b =>
                {
                    b.Property<int>("NotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotesId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Qa", b =>
                {
                    b.Property<int>("Qid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ans")
                        .HasColumnType("longtext");

                    b.Property<string>("Hint")
                        .HasColumnType("longtext");

                    b.Property<string>("Op1")
                        .HasColumnType("longtext");

                    b.Property<string>("Op2")
                        .HasColumnType("longtext");

                    b.Property<string>("Op3")
                        .HasColumnType("longtext");

                    b.Property<string>("Op4")
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .HasColumnType("longtext");

                    b.Property<int?>("SkillQuizId")
                        .HasColumnType("int");

                    b.HasKey("Qid");

                    b.HasIndex("SkillQuizId");

                    b.ToTable("Qas");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Review", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Rname")
                        .HasColumnType("longtext");

                    b.Property<int?>("Training")
                        .HasColumnType("int");

                    b.Property<int?>("UserDetail")
                        .HasColumnType("int");

                    b.HasKey("RId");

                    b.HasIndex("CourseId");

                    b.HasIndex("Training");

                    b.HasIndex("UserDetail");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("KaniniAcademy.Models.SkillQuiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("longblob");

                    b.Property<string>("Topic")
                        .HasColumnType("longtext");

                    b.HasKey("QuizId");

                    b.ToTable("SkillQuizzes");
                });

            modelBuilder.Entity("KaniniAcademy.Models.StatusOfLearner", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseCompletion")
                        .HasColumnType("int");

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.HasIndex("CourseID");

                    b.HasIndex("UserID");

                    b.ToTable("StatusOfLearners");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Submission", b =>
                {
                    b.Property<int>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Work")
                        .HasColumnType("longtext");

                    b.HasKey("SubId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Training", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("longblob");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext");

                    b.Property<string>("Tname")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Video")
                        .HasColumnType("longblob");

                    b.HasKey("Tid");

                    b.HasIndex("CreatorId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Usability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Usability");
                });

            modelBuilder.Entity("KaniniAcademy.Models.UserDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<long?>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("SkillQuizId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PointId");

                    b.HasIndex("SkillQuizId");

                    b.HasIndex("UserId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Blog", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Creator", null)
                        .WithMany("Blogs")
                        .HasForeignKey("CreatorId");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Course", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Creator", "Creator")
                        .WithMany("Courses")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("KaniniAcademy.Models.CourseResource", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Course", "Course")
                        .WithMany("CourseResources")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("KaniniAcademy.Models.CtcReg", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Certificate", "Certificate")
                        .WithMany("CtcReg")
                        .HasForeignKey("CertificateId");

                    b.HasOne("KaniniAcademy.Models.Course", "Course")
                        .WithMany("Ctcs")
                        .HasForeignKey("CourseId");

                    b.HasOne("KaniniAcademy.Models.Training", "Trainings")
                        .WithMany("ctcs")
                        .HasForeignKey("TrainingId");

                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserDetail")
                        .WithMany("CtcRegs")
                        .HasForeignKey("UserId");

                    b.Navigation("Certificate");

                    b.Navigation("Course");

                    b.Navigation("Trainings");

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("KaniniAcademy.Models.FreeResource", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Creator", null)
                        .WithMany("FreeResources")
                        .HasForeignKey("CreatorId");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Note", b =>
                {
                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserDetail")
                        .WithMany("Notes")
                        .HasForeignKey("UserId");

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Qa", b =>
                {
                    b.HasOne("KaniniAcademy.Models.SkillQuiz", "SkillQuiz")
                        .WithMany("Qas")
                        .HasForeignKey("SkillQuizId");

                    b.Navigation("SkillQuiz");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Review", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Course", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId");

                    b.HasOne("KaniniAcademy.Models.Training", "TraningId")
                        .WithMany("Reviews")
                        .HasForeignKey("Training");

                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserId")
                        .WithMany("Reviews")
                        .HasForeignKey("UserDetail");

                    b.Navigation("TraningId");

                    b.Navigation("UserId");
                });

            modelBuilder.Entity("KaniniAcademy.Models.StatusOfLearner", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Course", "Course")
                        .WithMany("StatusOfLearners")
                        .HasForeignKey("CourseID");

                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserDetail")
                        .WithMany("StatusOfLearner")
                        .HasForeignKey("UserID");

                    b.Navigation("Course");

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Submission", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Training", "Training")
                        .WithMany("Submissions")
                        .HasForeignKey("TrainingId");

                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserDetail")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Training");

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Training", b =>
                {
                    b.HasOne("KaniniAcademy.Models.Creator", "Creator")
                        .WithMany("Training")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Point", b =>
                {
                    b.HasOne("KaniniAcademy.Models.SkillQuiz", "SkillQuiz")
                        .WithMany("Points")
                        .HasForeignKey("SkillQuizId");

                    b.HasOne("KaniniAcademy.Models.UserDetail", "UserDetail")
                        .WithMany("Points")
                        .HasForeignKey("UserId");

                    b.Navigation("SkillQuiz");

                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Certificate", b =>
                {
                    b.Navigation("CtcReg");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Course", b =>
                {
                    b.Navigation("CourseResources");

                    b.Navigation("Ctcs");

                    b.Navigation("Reviews");

                    b.Navigation("StatusOfLearners");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Creator", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Courses");

                    b.Navigation("FreeResources");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("KaniniAcademy.Models.SkillQuiz", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Qas");
                });

            modelBuilder.Entity("KaniniAcademy.Models.Training", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Submissions");

                    b.Navigation("ctcs");
                });

            modelBuilder.Entity("KaniniAcademy.Models.UserDetail", b =>
                {
                    b.Navigation("CtcRegs");

                    b.Navigation("Notes");

                    b.Navigation("Points");

                    b.Navigation("Reviews");

                    b.Navigation("StatusOfLearner");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
